[package]
name = "slice-ext"
description = "Useful extensions to slices and iterable types"
version = "0.1.1"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
repository = "https://github.com/ryankurte/rust-slice-ext"
edition = "2018"
license = "MIT"

[dependencies]
